### ISSUE TITLE
Football::Team() not found

### ISSUE THREAD

**Issue by ZozoozoZ** [sorare/api#555] opened 2023-12-08 15:48 UTC
I am not able to get information on a club given is nodeid, I am getting the below error. Am I doing something wrong ?

Eg for Club:8be45830-3733-4a56-a183-bd4ba4c921ee

![image](https://github.com/sorare/api/assets/92556242/c9dd188b-bcd8-4ada-9412-90cc8d32afeb)
```
query retrieveClubWithNodeId($id: ID!) {
    node(id:$id) {
        ... on Club {
          id
          slug
        }
    }
}

{"id": "Club:42b054fb-1ba3-4547-857b-97b3f229abc7"}
```

I can retrieve the club with the 'club(slug)' query thought :
![image](https://github.com/sorare/api/assets/92556242/d1a5bc54-449d-46f2-afac-94f40b0bfeac)

**Comment by thom-des** [comment] 2024-04-23 08:45
Closing as the issue is not reproductible :

```
query {
  node(id: "Club:8be45830-3733-4a56-a183-bd4ba4c921ee") {
    ... on Club {
      id
      slug
    }
  }
}
```

```
{
  "data": {
    "node": {
      "id": "Club:8be45830-3733-4a56-a183-bd4ba4c921ee",
      "slug": "manchester-city-manchester"
    }
  }
}
```

**Closed by thom-des** 2024-04-23 08:45 UTC
