### ISSUE TITLE
500 Error on allNfts endpoint

### ISSUE THREAD

**Issue by jeremyallencpa** [sorare/api#296] opened 2022-09-28 13:34 UTC
I am getting a 500 internal server error when I try to paginate through the query in the screenshots below (it occurs when I get to the third page).

The pictures are in order (1 = image, 2 = image (1), 3 = image (2)) where image (2).png is the third iteration where I am encountering the 500 error.

The query that is causing the error is:
``query {
  tokens {
    allNfts(after: "WyIwMDAxOTBlOC0xYjIxLTRmYTktYjFkYS02YjA1Yzc5YTE2ZTgiXQ") {
      nodes {
        slug
        id
        assetId
        collectionName
        pictureUrl
        name
        contractAddress
        ethereumId
        owner {
          address
          blockchain
        }
        ownershipHistory {
          address
          blockchain
          from
          id
          priceFiat {
            usd
            eur
            gbp
          }
          priceWei
          transferType
        }
        metadata {
          ... on TokenCardMetadataInterface {
            teamSlug
            rarity
            serialNumber
            playerSlug
            playerDisplayName
            seasonStartYear
            ... on TokenBaseballMetadata {
              playerPositions
            }
          }
        }
      }
      pageInfo {
        endCursor
        hasNextPage
        hasPreviousPage
        startCursor
      }
    }
  }
}``

![image](https://user-images.githubusercontent.com/55819793/192792359-26106ef2-c8bc-4c6a-b32e-b0aea1623a9e.png)
![image (1)](https://user-images.githubusercontent.com/55819793/192792354-317badf9-f192-459d-8113-3f7bfdbfb502.png)
![image (2)](https://user-images.githubusercontent.com/55819793/192792356-e965f116-8a84-4e98-b180-a7f5ece21913.png)

**Comment by redox** [comment] 2022-09-28 19:50
We're investigating; I'm reproducing as well.

**Comment by redox** [comment] 2022-09-28 20:14
We found the root cause; we'll work on a fix - ETA most probably 24h from now.

**Comment by redox** [comment] 2022-09-29 11:26
This is now fixed @jeremyallencpa ; thank you for reporting it !

**Closed by redox** 2022-09-29 11:26 UTC

**Comment by zdick** [comment] 2022-10-29 07:46
Same issue here, only with FOOTBALL cards, using API key.

query ($cursor: String, $sport: [Sport!]!) { tokens { allNfts(after: $cursor, sport: $sport) { nodes { assetId slug name privateMinPrice publicMinPrice liveSingleSaleOffer { blockchainId priceWei } owner { user { slug } } metadata { ... on TokenCardMetadataInterface { playerDisplayName playerSlug rarity } } } pageInfo { endCursor } } } }

variables: { "cursor": "WyIwMGQxMmZmYi1mNThmLTRmMWItYmJkYy0xOTE5YzYyNmY2ZGYiXQ", "sport": ["FOOTBALL"] }

response:
            [0] => HTTP/1.1 500 Internal Server Error
            [1] => Date: Sat, 29 Oct 2022 07:43:37 GMT
            [2] => Content-Type: text/html; charset=UTF-8
            [3] => Transfer-Encoding: chunked
            [4] => Connection: keep-alive
            [5] => x-request-id: c17b16f7-5839-410e-808c-8d80137e0388
            [6] => x-runtime: 0.444204
            [7] => strict-transport-security: max-age=63072000; includeSubDomains
            [8] => vary: Origin
            [9] => CF-Cache-Status: DYNAMIC
            [10] => Server: cloudflare
            [11] => CF-RAY: 761a48023d09b377-PRG
