### ISSUE TITLE
Stark Signatures Python

### ISSUE THREAD

**Issue by nachoroncero** [sorare/api#326] opened 2022-10-27 16:53 UTC
Hello,

I am trying to implement the JavaScript code to sign the limitOrder objetcs, but I do not know how to do it the JSON.stringfy(...) part.
```
const starkSignatures = limitOrders.map((limitOrder) => ({
  data: JSON.stringify(signLimitOrder(privateKey, limitOrder)),
  nonce: limitOrder.nonce,
  expirationTimestamp: limitOrder.expirationTimestamp,
  starkKey,
}));
```
How can I code a function like signLimitOrder(privateKey, limitOrder) ? Any help would be appreciated

**Comment by RaKueh** [comment] 2022-11-01 07:04
I am stuck at the same place. Appreciate any help!

**Comment by utay** [comment] 2022-11-01 18:39
Closing this one as a duplicate of https://github.com/sorare/api/issues/312

@RaKueh Please check the above issue, it should help you!

**Closed by utay** 2022-11-01 18:39 UTC
