### ISSUE TITLE
Cannot return null for non-nullable field Stats.season?

### ISSUE THREAD

**Issue by V1pr** [sorare/api#27] opened 2021-06-01 08:57 UTC
Hi,

I'm trying to run the following query in the playbook, but getting the above error. I've tried suppling the season.startyear, but no success.

```
{
	  user (slug: "my_manager_name") {
				cardsCount
				cards {
					id
				  name
				  player {
  					activeClub {
                name
            }
            displayName 
            matchName
            memberships {
              startDate
              aggregatedStats {
                goals
                season {
                  id
                  name
                }
                redCards
                yellowCards
              }
          	}
					}
	  	}
		}
}
```

**Comment by redox** [comment] 2021-12-22 17:22
Hey @V1pr , sorry for the delay; I'm taking over some of those issues. I cannot reproduce your issue and it seems to work my my slug:

```gql
{
	  user (slug: "sylvain_") {
				cardsCount
				paginatedCards {
          nodes {
            id
            name
            player {
              activeClub {
                  name
              }
              displayName 
              matchName
              memberships {
                startDate
                aggregatedStats {
                  goals
                  season {
                    id
                    name
                  }
                  redCards
                  yellowCards
                }
              }
            }
          }
	  	}
		}
}
```

Closing the issue, but feel free to comment to re-open it if you still experience an issue.

**Closed by redox** 2021-12-22 17:22 UTC
